# Generated by Django 5.2.7 on 2025-10-26 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataForm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('operation', 'Operation'), ('record', 'Record')], max_length=20)),
                ('item_id', models.IntegerField(help_text='ID of the deleted item')),
                ('item_name', models.CharField(help_text='Name/identifier of deleted item', max_length=255)),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for deletion')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data (e.g., record count, associated records, etc.)')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deletion Log',
                'verbose_name_plural': 'Deletion Logs',
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['-deleted_at'], name='DataForm_de_deleted_519007_idx'), models.Index(fields=['item_type', '-deleted_at'], name='DataForm_de_item_ty_309c5d_idx'), models.Index(fields=['deleted_by', '-deleted_at'], name='DataForm_de_deleted_4a9c4a_idx')],
            },
        ),
    ]
