# Generated by Django 5.2.7 on 2025-10-26 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataForm', '0002_deletionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='DataForm.operation'),
        ),
    ]
